package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

public class newSubPublicationWindowController {
	@FXML
	private TextField subPubTitleTF;
	@FXML
	private TextField subPubAuthorTF;
	@FXML
	private TextField subPubCategoryTF;
	@FXML
	private Button subPubAddAuthorBtn;
	@FXML
	private Button subPubAddCategoryBtn;
	@FXML
	private Button subPubSaveBtn;

	// Event Listener on Button[#subPubSaveBtn].onMouseClicked
	@FXML
	public void saveSubPublication(MouseEvent event) {
		// TODO Autogenerated
	}
}
